name: Update Lottery API

on:
  schedule:
    # Run daily at 2 AM UTC (adjust timezone as needed)
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [ main ]

jobs:
  update-api:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyexcel
        
    - name: Download lottery data
      run: |
        python scripts/lottery_downloader.py Federal federal
        
    - name: Convert Excel to CSV
      run: |
        python scripts/xlsx_to_csv.py federal.xlsx federal.csv
        
    - name: Generate API files
      run: |
        python scripts/federal_csv_to_api.py federal.csv
        
    - name: Create index.html for GitHub Pages
      run: |
        python scripts/create_github_pages.py
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        force_orphan: true