# .github/workflows/update-lottery-api.yml
name: Update Lottery API
on:
  schedule:
    - cron: '0 8,20 * * *'  # Run at 8 AM and 8 PM UTC (twice daily)
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [main]
    paths: ['scripts/**'] # Only run if scripts change

jobs:
  update-api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm init -y
          npm install xlsx axios
      
      - name: Download and process lottery data
        run: node scripts/process-federal.js
        env:
          LOTTERY_URL: 'https://servicebus2.caixa.gov.br/portaldeloterias/api/resultados/download?modalidade=Federal'
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4